name: " ⏳  Gitea Mirror Setup"

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: varunsridharan/action-gitea-mirror@main
        name: " ⏳ Setting Up Mirror"
        with:
          gitea_host: 'https://codeberg.org/printf-app-data/'
          gitea_username: 'printftech'
          gitea_accesstoken: '30c701295e2fc32b8bd23ed0e8fb83ca7e10c56e'
          gitea_gist_prefix: "gist"
          gitea_gist_surfix: ""
